// src/pages/SalesAndRevenue.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowTrendingUpIcon, // Replaced ChartBarIcon
  Squares2X2Icon,       // Replaced ChartPieIcon
  SquaresPlusIcon,      // Replaced TableCellsIcon
  CreditCardIcon,
} from '@heroicons/react/24/outline';

const reportCards = [
  {
    to: '/reports/sales',
    title: 'Sales Report',
    description: 'View overall sales transactions within a specific date range.',
    icon: <ArrowTrendingUpIcon className="h-8 w-8 text-blue-500" />,
    color: 'blue'
  },
  {
    to: '/reports/item-wise-sales',
    title: 'Item-wise Sales Report',
    description: 'Analyze sales performance by individual menu items.',
    icon: <Squares2X2Icon className="h-8 w-8 text-green-500" />,
    color: 'green'
  },
  {
    to: '/reports/table-wise-sales',
    title: 'Table-wise Sales Report',
    description: 'Track sales and revenue generated by each table.',
    icon: <SquaresPlusIcon className="h-8 w-8 text-purple-500" />,
    color: 'purple'
  },
  {
    to: '/reports/payment-mode',
    title: 'Payment Mode Report',
    description: 'Breakdown of sales by payment method like cash, card, etc.',
    icon: <CreditCardIcon className="h-8 w-8 text-yellow-500" />,
    color: 'yellow'
  },
];

const SalesAndRevenue = () => {
  return (
    <div className="p-6 bg-gray-50 min-h-full">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-800">Sales & Revenue Reports</h1>
        <p className="text-gray-500 mt-1">Select a report type to view details.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {reportCards.map((card) => (
          <Link
            key={card.title}
            to={card.to}
            className="group bg-white rounded-xl shadow-md p-6 flex flex-col justify-between hover:shadow-xl hover:-translate-y-1 transition-all duration-300 cursor-pointer border border-gray-200"
          >
            <div>
              <div className="mb-4">{card.icon}</div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">{card.title}</h3>
              <p className="text-gray-600 text-sm">{card.description}</p>
            </div>
            <div className="mt-6">
              <span className={`font-semibold text-${card.color}-600 group-hover:text-${card.color}-800 transition-colors`}>
                View Report &rarr;
              </span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default SalesAndRevenue;